import {createError} from "h3";
import {DiscoverProviderModelsRequestDtoSchema, type DiscoverProviderModelsRequestDto, type ModelProviderDraftDto} from "nbook/shared/dto/app-settings.dto";
import {loadGlobalEffectiveConfigSync} from "nbook/server/config/config-service";
import {discoverProviderModels, withSavedProviderApiKey} from "nbook/server/utils/model-settings";
import {validateBody} from "nbook/server/utils/novel-chapter";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Config"
    ],
    "summary": "Discover available models from a provider",
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "provider": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string",
                                    "minLength": 1,
                                    "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]*$"
                                },
                                "name": {
                                    "type": "string",
                                    "minLength": 1
                                },
                                "api": {
                                    "default": null,
                                    "nullable": true,
                                    "type": "string",
                                    "minLength": 1
                                },
                                "options": {
                                    "type": "object",
                                    "properties": {
                                        "apiKey": {
                                            "default": "",
                                            "type": "string"
                                        },
                                        "baseURL": {
                                            "default": "",
                                            "type": "string"
                                        },
                                        "proxy": {
                                            "default": "",
                                            "type": "string"
                                        },
                                        "timeoutMs": {
                                            "default": null,
                                            "nullable": true,
                                            "type": "integer",
                                            "exclusiveMinimum": true,
                                            "maximum": 9007199254740991
                                        },
                                        "requestOptions": {
                                            "default": {},
                                            "type": "object",
                                            "additionalProperties": {
                                                "$ref": "#/definitions/__schema0"
                                            }
                                        }
                                    },
                                    "required": [
                                        "apiKey",
                                        "baseURL",
                                        "proxy",
                                        "timeoutMs",
                                        "requestOptions"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "required": [
                                "id",
                                "name",
                                "api",
                                "options"
                            ],
                            "additionalProperties": false
                        }
                    },
                    "required": [
                        "provider"
                    ],
                    "additionalProperties": false,
                    "definitions": {
                        "__schema0": {
                            "anyOf": [
                                {
                                    "type": "string"
                                },
                                {
                                    "type": "number"
                                },
                                {
                                    "type": "boolean"
                                },
                                {
                                    "type": "string",
                                    "nullable": true,
                                    "enum": [
                                        null
                                    ]
                                },
                                {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/__schema0"
                                    }
                                },
                                {
                                    "type": "object",
                                    "additionalProperties": {
                                        "$ref": "#/definitions/__schema0"
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "models": {
                                "default": [],
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "string",
                                            "minLength": 1
                                        },
                                        "name": {
                                            "type": "string",
                                            "minLength": 1
                                        },
                                        "group": {}
                                    },
                                    "required": [
                                        "id",
                                        "name",
                                        "group"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "message": {
                                "type": "string",
                                "minLength": 1
                            }
                        },
                        "required": [
                            "models",
                            "message"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});

/**
 * 远程模型发现。草稿未携带明文 API Key 时，回退读取已保存的 Global Config secret。
 */
export default defineEventHandler(async (event) => {
    const body = await validateBody<DiscoverProviderModelsRequestDto>(event, DiscoverProviderModelsRequestDtoSchema);
    try {
        return await discoverProviderModels(withSavedApiKey(body.provider));
    } catch (error) {
        throw createError({
            statusCode: resolveDiscoveryStatusCode(error),
            message: error instanceof Error ? error.message : "Provider 模型发现失败",
        });
    }
});

/**
 * 补齐设置页不会回传的已保存 API Key。
 */
function withSavedApiKey(providerDraft: ModelProviderDraftDto): ModelProviderDraftDto {
    const savedApiKey = loadGlobalEffectiveConfigSync().models.providers[providerDraft.id]?.options.apiKey ?? "";
    return withSavedProviderApiKey(providerDraft, savedApiKey);
}

/**
 * 将远程发现失败映射成稳定 HTTP 状态。
 */
function resolveDiscoveryStatusCode(error: unknown): number {
    const message = error instanceof Error ? error.message : "";
    if (message.includes("缺少 API Base")) {
        return 400;
    }
    if (message.includes("HTTP 401") || message.includes("HTTP 403")) {
        return 401;
    }
    return 502;
}
