import {CheckProviderRequestDtoSchema, type CheckProviderRequestDto} from "nbook/shared/dto/app-settings.dto";
import {loadGlobalEffectiveConfigSync} from "nbook/server/config/config-service";
import {checkProviderConnection, withSavedProviderApiKey} from "nbook/server/utils/model-settings";
import {validateBody} from "nbook/server/utils/novel-chapter";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Config"
    ],
    "summary": "Check connectivity of a model provider",
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "provider": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string",
                                    "minLength": 1,
                                    "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]*$"
                                },
                                "name": {
                                    "type": "string",
                                    "minLength": 1
                                },
                                "api": {
                                    "default": null,
                                    "nullable": true,
                                    "type": "string",
                                    "minLength": 1
                                },
                                "options": {
                                    "type": "object",
                                    "properties": {
                                        "apiKey": {
                                            "default": "",
                                            "type": "string"
                                        },
                                        "baseURL": {
                                            "default": "",
                                            "type": "string"
                                        },
                                        "proxy": {
                                            "default": "",
                                            "type": "string"
                                        },
                                        "timeoutMs": {
                                            "default": null,
                                            "nullable": true,
                                            "type": "integer",
                                            "exclusiveMinimum": true,
                                            "maximum": 9007199254740991
                                        },
                                        "requestOptions": {
                                            "default": {},
                                            "type": "object",
                                            "additionalProperties": {
                                                "$ref": "#/definitions/__schema0"
                                            }
                                        }
                                    },
                                    "required": [
                                        "apiKey",
                                        "baseURL",
                                        "proxy",
                                        "timeoutMs",
                                        "requestOptions"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "required": [
                                "id",
                                "name",
                                "api",
                                "options"
                            ],
                            "additionalProperties": false
                        },
                        "models": {
                            "default": [],
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "minLength": 1
                                    },
                                    "id": {
                                        "type": "string",
                                        "minLength": 1
                                    },
                                    "group": {},
                                    "provider": {},
                                    "api": {
                                        "default": null,
                                        "nullable": true,
                                        "type": "string",
                                        "minLength": 1
                                    },
                                    "baseUrl": {},
                                    "reasoning": {
                                        "default": null,
                                        "nullable": true,
                                        "type": "boolean"
                                    },
                                    "input": {
                                        "default": null,
                                        "nullable": true,
                                        "minItems": 1,
                                        "type": "array",
                                        "items": {
                                            "type": "string",
                                            "enum": [
                                                "text",
                                                "image"
                                            ]
                                        }
                                    },
                                    "maxTokens": {
                                        "default": null,
                                        "nullable": true,
                                        "type": "integer",
                                        "exclusiveMinimum": true,
                                        "maximum": 9007199254740991
                                    },
                                    "cost": {
                                        "default": null,
                                        "nullable": true,
                                        "type": "object",
                                        "properties": {
                                            "input": {
                                                "default": 0,
                                                "type": "number"
                                            },
                                            "output": {
                                                "default": 0,
                                                "type": "number"
                                            },
                                            "cacheRead": {
                                                "default": 0,
                                                "type": "number"
                                            },
                                            "cacheWrite": {
                                                "default": 0,
                                                "type": "number"
                                            }
                                        },
                                        "required": [
                                            "input",
                                            "output",
                                            "cacheRead",
                                            "cacheWrite"
                                        ],
                                        "additionalProperties": false
                                    },
                                    "compat": {
                                        "default": null,
                                        "nullable": true,
                                        "type": "object",
                                        "additionalProperties": {
                                            "$ref": "#/definitions/__schema1"
                                        }
                                    },
                                    "contextWindowTokens": {
                                        "default": null,
                                        "nullable": true,
                                        "type": "integer",
                                        "exclusiveMinimum": true,
                                        "maximum": 9007199254740991
                                    }
                                },
                                "required": [
                                    "name",
                                    "id",
                                    "group",
                                    "provider",
                                    "api",
                                    "baseUrl",
                                    "reasoning",
                                    "input",
                                    "maxTokens",
                                    "cost",
                                    "compat",
                                    "contextWindowTokens"
                                ],
                                "additionalProperties": false
                            }
                        },
                        "useSavedApiKey": {
                            "default": true,
                            "type": "boolean"
                        },
                        "useSavedModels": {
                            "default": true,
                            "type": "boolean"
                        }
                    },
                    "required": [
                        "provider",
                        "models",
                        "useSavedApiKey",
                        "useSavedModels"
                    ],
                    "additionalProperties": false,
                    "definitions": {
                        "__schema0": {
                            "anyOf": [
                                {
                                    "type": "string"
                                },
                                {
                                    "type": "number"
                                },
                                {
                                    "type": "boolean"
                                },
                                {
                                    "type": "string",
                                    "nullable": true,
                                    "enum": [
                                        null
                                    ]
                                },
                                {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/__schema0"
                                    }
                                },
                                {
                                    "type": "object",
                                    "additionalProperties": {
                                        "$ref": "#/definitions/__schema0"
                                    }
                                }
                            ]
                        },
                        "__schema1": {
                            "anyOf": [
                                {
                                    "type": "string"
                                },
                                {
                                    "type": "number"
                                },
                                {
                                    "type": "boolean"
                                },
                                {
                                    "type": "string",
                                    "nullable": true,
                                    "enum": [
                                        null
                                    ]
                                },
                                {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/__schema1"
                                    }
                                },
                                {
                                    "type": "object",
                                    "additionalProperties": {
                                        "$ref": "#/definitions/__schema1"
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "success": {
                                "type": "boolean"
                            },
                            "latencyMs": {
                                "nullable": true,
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 9007199254740991
                            },
                            "message": {
                                "type": "string",
                                "minLength": 1
                            }
                        },
                        "required": [
                            "success",
                            "latencyMs",
                            "message"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});

/**
 * Provider 连通性测试。草稿未携带明文 API Key 时，回退读取已保存的 Global Config secret。
 */
export default defineEventHandler(async (event) => {
    const body = await validateBody<CheckProviderRequestDto>(event, CheckProviderRequestDtoSchema);
    const savedProvider = loadGlobalEffectiveConfigSync().models.providers[body.provider.id];
    const provider = body.useSavedApiKey
        ? withSavedProviderApiKey(body.provider, savedProvider?.options.apiKey)
        : body.provider;
    const modelDrafts = body.models.length > 0
        ? body.models
        : body.useSavedModels
            ? Object.values(savedProvider?.models ?? {})
                .filter((model) => model.enabled)
                .map((model) => ({
                    name: model.name,
                    id: model.id,
                    group: model.group,
                    provider: model.provider,
                    api: model.api,
                    baseUrl: model.baseUrl,
                    reasoning: model.reasoning,
                    input: model.input,
                    maxTokens: model.maxTokens,
                    cost: model.cost,
                    compat: model.compat,
                    contextWindowTokens: model.contextWindowTokens,
                }))
            : [];
    return checkProviderConnection(provider, modelDrafts);
});
