import {z} from "zod";
import {deleteWorkspacePath} from "nbook/server/workspace-files/workspace-files";
import {resolveWorkspaceRootInput} from "nbook/server/workspace-files/novel-workspace";
import {invalidateProjectWorkspaceIndexAfterMutation} from "nbook/server/workspace-files/project-workspace-index";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Workspace Files"
    ],
    "summary": "Delete a workspace file or directory",
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "root": {
                            "description": "Workspace root directory",
                            "type": "string"
                        },
                        "novelId": {
                            "description": "Novel id used to resolve isolated workspace",
                            "type": "string"
                        },
                        "workspaceKind": {
                            "description": "Use the global user assets workspace",
                            "type": "string",
                            "enum": [
                                "user-assets"
                            ]
                        },
                        "path": {
                            "type": "string",
                            "minLength": 1,
                            "description": "Path to delete"
                        },
                        "recursive": {
                            "default": false,
                            "description": "Delete recursively",
                            "type": "boolean"
                        }
                    },
                    "required": [
                        "path",
                        "recursive"
                    ],
                    "additionalProperties": false
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "success": {
                                "type": "boolean"
                            }
                        },
                        "required": [
                            "success"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});

const DeleteWorkspacePathBodySchema = z.object({
    projectPath: z.string().optional(),
    workspaceKind: z.literal("user-assets").optional(),
    path: z.string().trim().min(1, "path 不能为空"),
    recursive: z.boolean().optional().default(false),
});

/**
 * 删除工作区文件或目录。
 */
export default defineEventHandler(async (event) => {
    const body = DeleteWorkspacePathBodySchema.parse(await readBody(event));
    const root = await resolveWorkspaceRootInput(body);
    await deleteWorkspacePath(root, body.path, body.recursive);
    invalidateProjectWorkspaceIndexAfterMutation({root, workspaceKind: body.workspaceKind});
    return {success: true};
});
