import {readWorkspaceTextFile, statWorkspacePath} from "nbook/server/workspace-files/workspace-files";
import {resolveWorkspaceRootInput} from "nbook/server/workspace-files/novel-workspace";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Workspace Files"
    ],
    "summary": "Read a workspace text file",
    "parameters": [
        {
            "name": "path",
            "in": "query",
            "required": true,
            "schema": {
                "type": "string",
                "minLength": 1,
                "description": "File path to read"
            },
            "description": "File path to read"
        },
        {
            "name": "root",
            "in": "query",
            "required": false,
            "schema": {
                "description": "Workspace root directory",
                "type": "string"
            },
            "description": "Workspace root directory"
        },
        {
            "name": "novelId",
            "in": "query",
            "required": false,
            "schema": {
                "description": "Novel id used to resolve isolated workspace",
                "type": "string"
            },
            "description": "Novel id used to resolve isolated workspace"
        },
        {
            "name": "workspaceKind",
            "in": "query",
            "required": false,
            "schema": {
                "description": "Use the global user assets workspace",
                "type": "string",
                "enum": [
                    "user-assets"
                ]
            },
            "description": "Use the global user assets workspace"
        }
    ],
    "responses": {
        "200": {
            "description": "OK"
        }
    }
} as never,
});


/**
 * 读取工作区文本文件。
 */
export default defineEventHandler(async (event) => {
    const query = getQuery(event);
    const filePath = readRequiredQueryString(query.path, "path");
    const projectPath = typeof query.projectPath === "string" ? query.projectPath : undefined;
    const workspaceKind = query.workspaceKind === "user-assets" ? query.workspaceKind : undefined;
    const workspaceRoot = await resolveWorkspaceRootInput({projectPath, workspaceKind});
    const [node, content] = await Promise.all([
        statWorkspacePath(workspaceRoot, filePath),
        readWorkspaceTextFile(workspaceRoot, filePath),
    ]);

    return {
        path: node.path,
        absolutePath: node.absolutePath,
        entryType: node.entryType,
        editable: node.editable,
        mtimeMs: node.mtimeMs,
        content,
    };
});

/**
 * 读取必填查询字符串。
 */
function readRequiredQueryString(value: unknown, key: string): string {
    if (typeof value !== "string" || !value.trim()) {
        throw createError({statusCode: 400, message: `${key} 不能为空`});
    }
    return value.trim();
}
