import {z} from "zod";
import {renameWorkspacePath} from "nbook/server/workspace-files/workspace-files";
import {resolveWorkspaceRootInput} from "nbook/server/workspace-files/novel-workspace";
import {invalidateProjectWorkspaceIndexAfterMutation} from "nbook/server/workspace-files/project-workspace-index";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Workspace Files"
    ],
    "summary": "Rename or move a workspace path",
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "root": {
                            "description": "Workspace root directory",
                            "type": "string"
                        },
                        "novelId": {
                            "description": "Novel id used to resolve isolated workspace",
                            "type": "string"
                        },
                        "workspaceKind": {
                            "description": "Use the global user assets workspace",
                            "type": "string",
                            "enum": [
                                "user-assets"
                            ]
                        },
                        "from": {
                            "type": "string",
                            "minLength": 1,
                            "description": "Source path"
                        },
                        "to": {
                            "type": "string",
                            "minLength": 1,
                            "description": "Destination path"
                        }
                    },
                    "required": [
                        "from",
                        "to"
                    ],
                    "additionalProperties": false
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK"
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});

const RenameWorkspacePathBodySchema = z.object({
    projectPath: z.string().optional(),
    workspaceKind: z.literal("user-assets").optional(),
    from: z.string().trim().min(1, "from 不能为空"),
    to: z.string().trim().min(1, "to 不能为空"),
});

/**
 * 移动或重命名工作区路径。
 */
export default defineEventHandler(async (event) => {
    const body = RenameWorkspacePathBodySchema.parse(await readBody(event));
    const root = await resolveWorkspaceRootInput(body);
    const node = await renameWorkspacePath(root, body.from, body.to);
    invalidateProjectWorkspaceIndexAfterMutation({root, workspaceKind: body.workspaceKind});
    return node;
});
