import {z} from "zod";
import {createError} from "h3";
import {readWorkspaceTextFile, statWorkspacePath, type WorkspaceFileNode} from "nbook/server/workspace-files/workspace-files";
import {buildWorkspaceWriteConflict} from "nbook/server/workspace-files/workspace-file-conflict";
import {resolveWorkspaceRootInput} from "nbook/server/workspace-files/novel-workspace";
import {invalidateProjectWorkspaceIndexAfterMutation} from "nbook/server/workspace-files/project-workspace-index";
import {assertProjectOpenForRoot} from "nbook/server/workspace-files/project-open-guard";
import {USER_LOCAL_ACTOR, writeWorkspaceTextFileTracked} from "nbook/server/workspace-history/tracked-workspace-files";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Workspace Files"
    ],
    "summary": "Write content to a workspace file",
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "root": {
                            "description": "Workspace root directory",
                            "type": "string"
                        },
                        "novelId": {
                            "description": "Novel id used to resolve isolated workspace",
                            "type": "string"
                        },
                        "workspaceKind": {
                            "description": "Use the global user assets workspace",
                            "type": "string",
                            "enum": [
                                "user-assets"
                            ]
                        },
                        "path": {
                            "type": "string",
                            "minLength": 1,
                            "description": "File path"
                        },
                        "content": {
                            "type": "string",
                            "description": "File content"
                        }
                    },
                    "required": [
                        "path",
                        "content"
                    ],
                    "additionalProperties": false
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK"
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});



const WriteWorkspaceFileBodySchema = z.object({
    projectPath: z.string().optional(),
    workspaceKind: z.literal("user-assets").optional(),
    path: z.string().trim().min(1, "path 不能为空"),
    content: z.string(),
    baseContent: z.string().optional(),
    expectedMtimeMs: z.number().nullable().optional(),
    force: z.boolean().optional().default(false),
});

/**
 * 覆盖写入工作区文本文件。
 */
export default defineEventHandler(async (event) => {
    const body = WriteWorkspaceFileBodySchema.parse(await readBody(event));
    const root = await resolveWorkspaceRootInput(body);
    assertProjectOpenForRoot(root);
    // 冲突检测已读到的写前内容，直接作为记账 before 复用（省一次读盘）。
    let knownBefore: string | null | undefined = undefined;
    if (!body.force && body.expectedMtimeMs !== undefined) {
        const remoteState = await readRemoteState(root, body.path);
        knownBefore = remoteState.node === null ? null : remoteState.content;
        const actualMtimeMs = remoteState.node?.mtimeMs ?? null;
        if (actualMtimeMs !== body.expectedMtimeMs) {
            const conflict = await buildWorkspaceWriteConflict({
                path: body.path,
                expectedMtimeMs: body.expectedMtimeMs,
                actualMtimeMs,
                baseContent: body.baseContent ?? "",
                localContent: body.content,
                remoteContent: remoteState.content,
                remoteExists: remoteState.node !== null,
                node: remoteState.node,
            });
            throw createError({
                statusCode: 409,
                statusMessage: "Workspace file write conflict",
                message: "真实文件已被修改，请先处理冲突",
                data: conflict,
            });
        }
    }

    await writeWorkspaceTextFileTracked({root, filePath: body.path, content: body.content, actor: USER_LOCAL_ACTOR, knownBefore});
    invalidateProjectWorkspaceIndexAfterMutation({root, workspaceKind: body.workspaceKind});
    return statWorkspacePath(root, body.path);
});

/**
 * 读取当前真实文件状态；文件被外部删除时返回空内容和空节点。
 */
async function readRemoteState(root: string | undefined, filePath: string): Promise<{
    node: WorkspaceFileNode | null;
    content: string;
}> {
    try {
        const [node, content] = await Promise.all([
            statWorkspacePath(root, filePath),
            readWorkspaceTextFile(root, filePath),
        ]);
        return {node, content};
    } catch (error) {
        if (typeof error === "object" && error !== null && "code" in error && (error as {code?: string}).code === "ENOENT") {
            return {
                node: null,
                content: "",
            };
        }
        throw error;
    }
}
