import {
    CreateStoryActRequestDtoSchema,
    CreateStoryChapterRequestDtoSchema,
    CreateStoryPhaseRequestDtoSchema,
    CreateStorySceneRequestDtoSchema,
    CreateStoryThreadRequestDtoSchema,
    ReorderStoryPhasesRequestDtoSchema,
    ReorderStoryScenesRequestDtoSchema,
    ReorderStoryThreadsRequestDtoSchema,
    UpdateStoryActRequestDtoSchema,
    UpdateStoryChapterRequestDtoSchema,
    UpdateStoryPhaseRequestDtoSchema,
    UpdateStoryRequestDtoSchema,
    UpdateStorySceneRequestDtoSchema,
    UpdateStoryThreadRequestDtoSchema,
    type CreateStoryActRequestDto,
    type CreateStoryChapterRequestDto,
    type CreateStoryPhaseRequestDto,
    type CreateStorySceneRequestDto,
    type CreateStoryThreadRequestDto,
    type ReorderStoryPhasesRequestDto,
    type ReorderStoryScenesRequestDto,
    type ReorderStoryThreadsRequestDto,
    type UpdateStoryActRequestDto,
    type UpdateStoryChapterRequestDto,
    type UpdateStoryPhaseRequestDto,
    type UpdateStoryRequestDto,
    type UpdateStorySceneRequestDto,
    type UpdateStoryThreadRequestDto,
} from "nbook/shared/dto/plot.dto";
import type {H3Event} from "h3";
import {plotFacade} from "nbook/server/plot";
import {parseEntityId, requireProjectPathQuery, validateBody} from "nbook/server/utils/novel-chapter";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Plot Scenes"
    ],
    "summary": "Get a story scene's filtered World Engine context via /projects/plot/scenes/:sceneId/world-context",
    "parameters": [
        {
            "name": "sceneId",
            "in": "path",
            "required": true,
            "schema": {
                "type": "string"
            }
        },
        {
            "name": "projectPath",
            "in": "query",
            "required": true,
            "schema": {
                "type": "string",
                "minLength": 1,
                "description": "Project Workspace path, for example workspace/<project>"
            },
            "description": "Project Workspace path, for example workspace/<project>"
        }
    ],
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "slices": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "string"
                                        },
                                        "time": {
                                            "type": "string"
                                        },
                                        "title": {
                                            "type": "string"
                                        },
                                        "summary": {
                                            "type": "string"
                                        },
                                        "kind": {
                                            "type": "string"
                                        },
                                        "patchCount": {
                                            "type": "integer",
                                            "minimum": 0,
                                            "maximum": 9007199254740991
                                        }
                                    },
                                    "required": [
                                        "id",
                                        "time",
                                        "title",
                                        "summary",
                                        "kind",
                                        "patchCount"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "subjectStates": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "subjectId": {
                                            "type": "string"
                                        },
                                        "type": {
                                            "type": "string"
                                        },
                                        "name": {
                                            "type": "string"
                                        },
                                        "attrs": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "$ref": "#/definitions/__schema0"
                                            }
                                        }
                                    },
                                    "required": [
                                        "subjectId",
                                        "type",
                                        "name",
                                        "attrs"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "unresolvedSubjectIds": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        },
                        "required": [
                            "slices",
                            "subjectStates",
                            "unresolvedSubjectIds"
                        ],
                        "additionalProperties": false,
                        "definitions": {
                            "__schema0": {
                                "anyOf": [
                                    {
                                        "type": "string",
                                        "nullable": true,
                                        "enum": [
                                            null
                                        ]
                                    },
                                    {
                                        "type": "boolean"
                                    },
                                    {
                                        "type": "number"
                                    },
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "array",
                                        "items": {
                                            "$ref": "#/definitions/__schema0"
                                        }
                                    },
                                    {
                                        "type": "object",
                                        "additionalProperties": {
                                            "$ref": "#/definitions/__schema0"
                                        }
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        }
    }
} as never,
});

/**
 * Project Path query 版本的 Plot API，避免把 workspace/<project> 放进 URL path 段。
 */
export default defineEventHandler(async (event) => {
    const projectPath = requireProjectPathQuery(event);
    const segments = readSegments(event);
    const method = event.method.toUpperCase();

    if (method === "GET" && matchSegments(segments, ["story"])) {
        return plotFacade.getStoryDto(projectPath);
    }
    if (method === "PATCH" && matchSegments(segments, ["story"])) {
        const body = await validateBody<UpdateStoryRequestDto>(event, UpdateStoryRequestDtoSchema);
        return plotFacade.updateStory(projectPath, body);
    }
    if (method === "GET" && matchSegments(segments, ["tree"])) {
        return plotFacade.getPlotTree(projectPath);
    }
    if (method === "GET" && matchSegments(segments, ["workbench"])) {
        return plotFacade.getPlotWorkbench(projectPath);
    }
    if (method === "GET" && matchSegments(segments, ["chapter"])) {
        return plotFacade.getChapterPlotDetailDto(projectPath, requireChapterIdQuery(event));
    }
    if (method === "GET" && matchSegments(segments, ["chapter-writer-brief"])) {
        return plotFacade.getChapterWriterBrief(projectPath, requireChapterIdQuery(event), readBriefModeQuery(event));
    }

    if (segments[0] === "phases") {
        return handlePhases(event, projectPath, method, segments);
    }
    if (segments[0] === "acts") {
        return handleActs(event, projectPath, method, segments);
    }
    if (segments[0] === "chapters") {
        return handleChapters(event, projectPath, method, segments);
    }
    if (segments[0] === "threads") {
        return handleThreads(event, projectPath, method, segments);
    }
    if (segments[0] === "scenes") {
        return handleScenes(event, projectPath, method, segments);
    }

    throw createError({statusCode: 404, message: "未知 Project Plot API"});
});

/** 承载树 Act(卷)CRUD。 */
async function handleActs(event: H3Event, projectPath: string, method: string, segments: string[]): Promise<unknown> {
    if (method === "POST" && matchSegments(segments, ["acts"])) {
        const body = await validateBody<CreateStoryActRequestDto>(event, CreateStoryActRequestDtoSchema);
        return plotFacade.createStoryAct(projectPath, body);
    }
    if (segments.length === 2) {
        const actId = parseEntityId("actId", segments[1] ?? "");
        if (method === "GET") return plotFacade.getStoryActDto(projectPath, actId);
        if (method === "PATCH") {
            const body = await validateBody<UpdateStoryActRequestDto>(event, UpdateStoryActRequestDtoSchema);
            return plotFacade.updateStoryAct(projectPath, actId, body);
        }
        if (method === "DELETE") return plotFacade.deleteStoryAct(projectPath, actId);
    }
    throw createError({statusCode: 404, message: "未知 Project Act API"});
}

/** 承载树 Chapter(章)CRUD,含 ChapterBrief 字段更新。 */
async function handleChapters(event: H3Event, projectPath: string, method: string, segments: string[]): Promise<unknown> {
    if (method === "POST" && matchSegments(segments, ["chapters"])) {
        const body = await validateBody<CreateStoryChapterRequestDto>(event, CreateStoryChapterRequestDtoSchema);
        return plotFacade.createStoryChapter(projectPath, body);
    }
    if (segments.length === 2) {
        const chapterId = parseEntityId("chapterId", segments[1] ?? "");
        if (method === "GET") return plotFacade.getStoryChapterDto(projectPath, chapterId);
        if (method === "PATCH") {
            const body = await validateBody<UpdateStoryChapterRequestDto>(event, UpdateStoryChapterRequestDtoSchema);
            return plotFacade.updateStoryChapter(projectPath, chapterId, body);
        }
        if (method === "DELETE") return plotFacade.deleteStoryChapter(projectPath, chapterId);
    }
    // GET /chapters/:id/prose:列出通过 frontmatter `chapter: <name>` 反指本章的正文节点。
    if (method === "GET" && segments.length === 3 && segments[2] === "prose") {
        const chapterId = parseEntityId("chapterId", segments[1] ?? "");
        const chapter = await plotFacade.getStoryChapterDto(projectPath, chapterId);
        return plotFacade.findProseForChapter(projectPath, chapter.name);
    }
    throw createError({statusCode: 404, message: "未知 Project Chapter API"});
}

async function handlePhases(event: H3Event, projectPath: string, method: string, segments: string[]): Promise<unknown> {
    if (method === "POST" && matchSegments(segments, ["phases"])) {
        const body = await validateBody<CreateStoryPhaseRequestDto>(event, CreateStoryPhaseRequestDtoSchema);
        return plotFacade.createStoryPhase(projectPath, body);
    }
    if (method === "POST" && matchSegments(segments, ["phases", "reorder"])) {
        const body = await validateBody<ReorderStoryPhasesRequestDto>(event, ReorderStoryPhasesRequestDtoSchema);
        return plotFacade.reorderStoryPhases(projectPath, body);
    }
    if (segments.length === 2) {
        const phaseId = parseEntityId("phaseId", segments[1] ?? "");
        if (method === "GET") return plotFacade.getStoryPhaseDto(projectPath, phaseId);
        if (method === "PATCH") {
            const body = await validateBody<UpdateStoryPhaseRequestDto>(event, UpdateStoryPhaseRequestDtoSchema);
            return plotFacade.updateStoryPhase(projectPath, phaseId, body);
        }
        if (method === "DELETE") return plotFacade.deleteStoryPhase(projectPath, phaseId);
    }
    throw createError({statusCode: 404, message: "未知 Project Phase API"});
}

async function handleThreads(event: H3Event, projectPath: string, method: string, segments: string[]): Promise<unknown> {
    if (method === "POST" && matchSegments(segments, ["threads"])) {
        const body = await validateBody<CreateStoryThreadRequestDto>(event, CreateStoryThreadRequestDtoSchema);
        return plotFacade.createStoryThread(projectPath, body);
    }
    if (method === "POST" && matchSegments(segments, ["threads", "reorder"])) {
        const body = await validateBody<ReorderStoryThreadsRequestDto>(event, ReorderStoryThreadsRequestDtoSchema);
        return plotFacade.reorderStoryThreads(projectPath, body);
    }
    if (segments.length === 2) {
        const threadId = parseEntityId("threadId", segments[1] ?? "");
        if (method === "GET") return plotFacade.getStoryThreadDetailDto(projectPath, threadId);
        if (method === "PATCH") {
            const body = await validateBody<UpdateStoryThreadRequestDto>(event, UpdateStoryThreadRequestDtoSchema);
            return plotFacade.updateStoryThread(projectPath, threadId, body);
        }
        if (method === "DELETE") return plotFacade.deleteStoryThread(projectPath, threadId);
    }
    throw createError({statusCode: 404, message: "未知 Project Thread API"});
}

async function handleScenes(event: H3Event, projectPath: string, method: string, segments: string[]): Promise<unknown> {
    if (method === "POST" && matchSegments(segments, ["scenes"])) {
        const body = await validateBody<CreateStorySceneRequestDto>(event, CreateStorySceneRequestDtoSchema);
        return plotFacade.createStoryScene(projectPath, body);
    }
    if (method === "POST" && matchSegments(segments, ["scenes", "reorder"])) {
        const body = await validateBody<ReorderStoryScenesRequestDto>(event, ReorderStoryScenesRequestDtoSchema);
        return plotFacade.reorderStoryScenes(projectPath, body);
    }
    if (method === "GET" && segments.length === 3 && segments[2] === "world-context") {
        const sceneId = parseEntityId("sceneId", segments[1] ?? "");
        return plotFacade.getSceneWorldContext(projectPath, sceneId);
    }
    if (segments.length === 2) {
        const sceneId = parseEntityId("sceneId", segments[1] ?? "");
        if (method === "GET") return plotFacade.getStorySceneDetailDto(projectPath, sceneId);
        if (method === "PATCH") {
            const body = await validateBody<UpdateStorySceneRequestDto>(event, UpdateStorySceneRequestDtoSchema);
            return plotFacade.updateStoryScene(projectPath, sceneId, body);
        }
        if (method === "DELETE") return plotFacade.deleteStoryScene(projectPath, sceneId);
    }
    throw createError({statusCode: 404, message: "未知 Project Scene API"});
}

function readSegments(event: H3Event): string[] {
    const rawSegments = event.context.params?.segments;
    const segments = Array.isArray(rawSegments) ? rawSegments : typeof rawSegments === "string" ? rawSegments.split("/") : [];
    return segments.map((segment) => decodeURIComponent(segment)).filter(Boolean);
}

function matchSegments(left: string[], right: string[]): boolean {
    return left.length === right.length && left.every((segment, index) => segment === right[index]);
}

function requireChapterIdQuery(event: H3Event): number {
    const value = getQuery(event).chapterId;
    const text = typeof value === "string" ? value.trim() : "";
    if (!text) {
        throw createError({statusCode: 400, message: "chapterId query 不能为空"});
    }
    return parseEntityId("chapterId", text);
}

/** 读取 brief 防全知模式 query;缺省或非法一律回落 autonomous。 */
function readBriefModeQuery(event: H3Event): "autonomous" | "curated" {
    return getQuery(event).mode === "curated" ? "curated" : "autonomous";
}
