import {requireProjectPath} from "nbook/server/utils/novel-chapter";
import {deleteProjectWorkspace} from "nbook/server/workspace-files/project-workspace-delete";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Novels"
    ],
    "summary": "Delete a novel and its plot data",
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "success": {
                                "type": "boolean"
                            }
                        },
                        "required": [
                            "success"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        }
    }
} as never,
});


/**
 * 删除 Project Workspace 目录。
 */
export default defineEventHandler(async (event) => {
    const projectPath = requireProjectPath(event);
    await deleteProjectWorkspace(projectPath);

    return {
        success: true,
    };
});
